# Generated by Django 5.1.1 on 2024-09-30 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(verbose_name='Место')),
                ('action', models.TextField(verbose_name='Действие')),
                ('action_start_time', models.TimeField(verbose_name='Время начала действия')),
                ('action_time_seconds', models.PositiveIntegerField(verbose_name='Время на выполение действия в секундах')),
                ('period_days', models.PositiveIntegerField(verbose_name='Периодичность выполнения в днях')),
                ('is_beneficial', models.BooleanField(default=True, verbose_name='Полезная привычка')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
                ('reward_habbit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habbits.habbit', verbose_name='Приятная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
