# Generated by Django 5.1.1 on 2024-09-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habbits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbit',
            name='reward_habbit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_habbit', to='habbits.habbit', verbose_name='Приятная привычка'),
        ),
    ]
